=== KajuskaCZ/konfiguraceHernihoSveta/pikorova_karolina.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:simpleType name="pocasi_vyber">
    <xs:restriction base="xs:string">
        <xs:pattern value="slunečno|polojasno|deštivo|větrno|bouřka|sníh"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="filtr_vyber">
    <xs:restriction base="xs:string">
        <xs:pattern value="přesvětlený|světlý|žádný|tmavý|ztmavený"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="obloha_vyber">
    <xs:restriction base="xs:string">
        <xs:pattern value="den|noc|slunce|mraky|déšť|sníh|blesky"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="kvalita_vyber">
    <xs:restriction base="xs:string">
        <xs:pattern value="nízká|střední|vysoká|ultra"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="reputace_vyber">
    <xs:restriction base="xs:string">
        <xs:pattern value="nenáviděn|nepřátelé|neutrální|přátelé|povýšen|ctěn"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="zamereni_vyber">
    <xs:restriction base="xs:string">
        <xs:pattern value="lučištníci|léčitelé|kouzelníci|váečníci|černokněžníci|rytíři|obecné"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="vyskyt_vyber">
    <xs:restriction base="xs:string">
        <xs:pattern value="sever|jih|východ|západ|celá oblast"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="typ_odmeny_vyber">
    <xs:restriction base="xs:string">
        <xs:pattern value="odpad|normální|střední|vzácná|epická|legendární"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="trida_vyber">
    <xs:restriction base="xs:string">
        <xs:pattern value="válečník|lučištník|léčitel|kouzelník|černokněžník|rytíř|žádná"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:element name="konfigurace_oblasti">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="obecne_nastaveni">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="max_pocet_oblasti" type="xs:unsignedShort"/>
              <xs:element name="celkova_rozloha" type="xs:integer"/>
              <xs:element name="zvyrazneni_hranic" type="xs:boolean"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="oblasti">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="oblast" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nastaveni">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="filtr" type="filtr_vyber"/>
                          <xs:element name="viditelnost" type="xs:unsignedShort"/>
                          <xs:element name="pocasi">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="pocasi_vyber">
                                  <xs:attribute name="obloha" type="obloha_vyber"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="rozloha" type="xs:integer"/>
                          <xs:element name="hudba_playlist" type="xs:unsignedShort"/>
                          <xs:element name="voda">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="odstin" type="xs:unsignedShort"/>
                                <xs:element name="odraz" type="xs:boolean"/>
                                <xs:element name="kvalita" type="kvalita_vyber"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="urovne">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="min_uroven" type="xs:unsignedShort"/>
                          <xs:element name="min_uroven_nepratel" type="xs:unsignedShort"/>
                          <xs:element name="max_uroven_nepratel" type="xs:unsignedShort"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="frakce_v_oblasti">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="frakce" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="reputace">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="reputace_vyber">
                                        <xs:attribute name="body_na_zacatek" type="xs:unsignedShort"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="zamereni" type="zamereni_vyber"/>
                                <xs:element name="interaktivni_postavy">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="interaktivni_postava" maxOccurs="unbounded">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="moznost_zabit" type="xs:boolean"/>
                                            <xs:element name="ukoly">
                                              <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="ukol" maxOccurs="unbounded">
                                                    <xs:complexType>
                                                      <xs:sequence>
                                                        <xs:element name="popis" type="xs:string"/>
                                                        <xs:element name="odmena" type="xs:string"/>
                                                      </xs:sequence>
                                                      <xs:attribute name="id" type="xs:integer"/>
                                                      <xs:attribute name="u_nazev" type="xs:string"/>
                                                    </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                              </xs:complexType>
                                            </xs:element>
                                          </xs:sequence>
                                          <xs:attribute name="id" type="xs:integer"/>
                                          <xs:attribute name="jmeno" type="xs:string"/>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="f_nazev" type="xs:string"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="skupiny_nepratel">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="skupina_nepratel" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="vyskyt" type="vyskyt_vyber"/>
                                <xs:element name="min_pocet_jedincu" type="xs:unsignedShort"/>
                                <xs:element name="min_uroven_nepritele" type="xs:unsignedShort"/>
                                <xs:element name="min_typ_odmeny" type="typ_odmeny_vyber"/>
                              </xs:sequence>
                              <xs:attribute name="n_nazev" type="xs:string"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="hlavni_nepratele">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="hlavni_nepritel" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="level" type="xs:unsignedShort"/>
                                <xs:element name="pozice">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="x" type="xs:integer"/>
                                      <xs:element name="y" type="xs:integer"/>
                                      <xs:element name="z" type="xs:integer"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="dohled" type="xs:unsignedShort" />
                                <xs:element name="staty">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="zivoty">
                                        <xs:complexType>
                                          <xs:simpleContent>
                                            <xs:extension base="xs:unsignedShort">
                                              <xs:attribute name="rychlot_obnovy_zivotu" type="xs:decimal"/>
                                            </xs:extension>
                                          </xs:simpleContent>
                                        </xs:complexType>
                                      </xs:element>
                                      <xs:element name="pohyblivost">
                                        <xs:complexType>
                                          <xs:simpleContent>
                                            <xs:extension base="xs:unsignedShort">
                                              <xs:attribute name="rychlost_obnovy_pohyblivosti" type="xs:decimal"/>
                                            </xs:extension>
                                          </xs:simpleContent>
                                        </xs:complexType>
                                      </xs:element>
                                      <xs:element name="rychlost_utoku" type="xs:decimal"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="zvlastni_schpnost">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute name="zbran" type="xs:string"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="typ_odmeny">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="typ_odmeny_vyber">
                                        <xs:attribute name="xp" type="xs:integer"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="id" type="xs:integer"/>
                              <xs:attribute name="jmeno" type="xs:string"/>
                              <xs:attribute name="trida" type="trida_vyber"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="poklady">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="poklad" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="pozice">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="x" type="xs:integer"/>
                                      <xs:element name="y" type="xs:integer"/>
                                      <xs:element name="z" type="xs:integer"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="typ_odmeny">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="typ_odmeny_vyber">
                                        <xs:attribute name="xp" type="xs:integer"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="id" type="xs:integer"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="souboje">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="pvp" type="xs:boolean"/>
                          <xs:element name="arena" type="xs:boolean"/>
                          <xs:element name="potrebna_reputace" type="reputace_vyber"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:integer"/>
                  <xs:attribute name="o_nazev" type="xs:string"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== KajuskaCZ/konfiguraceHernihoSveta/pikorova_karolina.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Odkaz na projekt uložený na GitHub: https://github.com/KajuskaCZ/konfiguraceHernihoSveta -->
<konfigurace_oblasti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pikorova_karolina.xsd">
    <obecne_nastaveni>
        <max_pocet_oblasti>7</max_pocet_oblasti>
        <celkova_rozloha>9200</celkova_rozloha>
        <zvyrazneni_hranic>false</zvyrazneni_hranic>
    </obecne_nastaveni>
    <oblasti>
        <oblast id="1" o_nazev="Staré město">
            <nastaveni>
                <filtr>žádný</filtr>
                <viditelnost>50</viditelnost>
                <pocasi obloha="mraky">polojasno</pocasi>
                <rozloha>800</rozloha>
                <hudba_playlist>8</hudba_playlist>
                <voda>
                    <odstin>1</odstin>
                    <odraz>false</odraz>
                    <kvalita>střední</kvalita>
                </voda>
            </nastaveni>
            <urovne>
                <min_uroven>1</min_uroven>
                <min_uroven_nepratel>1</min_uroven_nepratel>
                <max_uroven_nepratel>10</max_uroven_nepratel>
            </urovne>
            <frakce_v_oblasti>
                <frakce f_nazev="Železní">
                    <reputace body_na_zacatek="0">přátelé</reputace>
                    <zamereni>obecné</zamereni>
                    <interaktivni_postavy>
                        <interaktivni_postava id="5" jmeno="Zeus">
                            <moznost_zabit>false</moznost_zabit>
                            <ukoly>
                                <ukol id="1" u_nazev="Zlatý prsten">
                                    <popis>Ve staré truhle v mém dřívějším domově jsem zapomněl svůj drahocený prsten. Přines mi ho a dám Ti odměnu.</popis>
                                    <odmena>Mědený prsten</odmena>
                                </ukol>
                                <ukol id="2" u_nazev="Kovář">
                                    <popis>Mým společníkem, jak jsi již jistě zjistil, je kovář Serpis. Poptej se ho na nejlepší zbroje v kraji.</popis>
                                    <odmena>Železné kalhoty s vyrytým znakem</odmena>
                                </ukol>
                                <ukol id="3" u_nazev="Polévka">
                                    <popis>Přines pět prasečích ocásků.</popis>
                                    <odmena>Vepřová polévka</odmena>
                                </ukol>
                            </ukoly>
                        </interaktivni_postava>
                    </interaktivni_postavy>
                </frakce>
            </frakce_v_oblasti>
            <skupiny_nepratel>
                <skupina_nepratel n_nazev="Jezdci">
                    <vyskyt>sever</vyskyt>
                    <min_pocet_jedincu>3</min_pocet_jedincu>
                    <min_uroven_nepritele>4</min_uroven_nepritele>
                    <min_typ_odmeny>střední</min_typ_odmeny>
                </skupina_nepratel>
                <skupina_nepratel n_nazev="Potulná zvěř">
                    <vyskyt>celá oblast</vyskyt>
                    <min_pocet_jedincu>1</min_pocet_jedincu>
                    <min_uroven_nepritele>1</min_uroven_nepritele>
                    <min_typ_odmeny>normální</min_typ_odmeny>
                </skupina_nepratel>
            </skupiny_nepratel>
            <hlavni_nepratele>
                <hlavni_nepritel id="1" jmeno="Borgah" trida="válečník">
                    <level>9</level>
                    <pozice>
                        <x>100</x>
                        <y>20</y>
                        <z>50</z>
                    </pozice>
                    <dohled>12</dohled>
                    <staty>
                        <zivoty rychlot_obnovy_zivotu="0.2">150</zivoty>
                        <pohyblivost rychlost_obnovy_pohyblivosti="0.5">70</pohyblivost>
                        <rychlost_utoku>0.2</rychlost_utoku>
                    </staty>
                    <zvlastni_schpnost zbran="žádná">vrh balvanem</zvlastni_schpnost>
                    <typ_odmeny xp="250">normální</typ_odmeny>
                </hlavni_nepritel>
                <hlavni_nepritel id="2" jmeno="Daurelis" trida="černokněžník">
                    <level>10</level>
                    <pozice>
                        <x>25</x>
                        <y>325</y>
                        <z>45</z>
                    </pozice>
                    <dohled>19</dohled>
                    <staty>
                        <zivoty rychlot_obnovy_zivotu="0.5">200</zivoty>
                        <pohyblivost rychlost_obnovy_pohyblivosti="0.5">85</pohyblivost>
                        <rychlost_utoku>0.2</rychlost_utoku>
                    </staty>
                    <zvlastni_schpnost zbran="temná magická hůl">ledový hrot</zvlastni_schpnost>
                    <typ_odmeny xp="300">střední</typ_odmeny>
                </hlavni_nepritel>
            </hlavni_nepratele>
            <poklady>
                <poklad id="250">
                    <pozice>
                        <x>0</x>
                        <y>200</y>
                        <z>25</z>
                    </pozice>
                    <typ_odmeny xp="20">střední</typ_odmeny>
                </poklad>
                <poklad id="251">
                    <pozice>
                        <x>348</x>
                        <y>526</y>
                        <z>40</z>
                    </pozice>
                    <typ_odmeny xp="50">vzácná</typ_odmeny>
                </poklad>
                <poklad id="252">
                    <pozice>
                        <x>250</x>
                        <y>654</y>
                        <z>60</z>
                    </pozice>
                    <typ_odmeny xp="50">vzácná</typ_odmeny>
                </poklad>
            </poklady>
            <souboje>
                <pvp>false</pvp>
                <arena>true</arena>
                <potrebna_reputace>nenáviděn</potrebna_reputace>
            </souboje>
        </oblast>
        <oblast id="2" o_nazev="Nejčarovnější les">
            <nastaveni>
                <filtr>tmavý</filtr>
                <viditelnost>40</viditelnost>
                <pocasi obloha="slunce">polojasno</pocasi>
                <rozloha>600</rozloha>
                <hudba_playlist>6</hudba_playlist>
                <voda>
                    <odstin>2</odstin>
                    <odraz>false</odraz>
                    <kvalita>střední</kvalita>
                </voda>
            </nastaveni>
            <urovne>
                <min_uroven>10</min_uroven>
                <min_uroven_nepratel>10</min_uroven_nepratel>
                <max_uroven_nepratel>20</max_uroven_nepratel>
            </urovne>
            <frakce_v_oblasti>
                <frakce f_nazev="Elfové">
                    <reputace body_na_zacatek="0">přátelé</reputace>
                    <zamereni>lučištníci</zamereni>
                    <interaktivni_postavy>
                        <interaktivni_postava id="7" jmeno="Mirime">
                            <moznost_zabit>false</moznost_zabit>
                            <ukoly>
                                <ukol id="4" u_nazev="Jasnovidec">
                                    <popis>Zjisti, kdo škodí elfům v jejich lesním domově.</popis>
                                    <odmena>Toulec a deset šípů s železným hrotem</odmena>
                                </ukol>
                            </ukoly>
                        </interaktivni_postava>
                    </interaktivni_postavy>
                </frakce>
                <frakce f_nazev="Dryády">
                    <reputace body_na_zacatek="500">neutrální</reputace>
                    <zamereni>léčitelé</zamereni>
                    <interaktivni_postavy>
                        <interaktivni_postava id="8" jmeno="Laticia">
                            <moznost_zabit>false</moznost_zabit>
                            <ukoly>
                                <ukol id="5" u_nazev="Kouzlo lesa">
                                    <popis>Prozkoumej ještě nikým neprobádané jižní části lesa. Dej si však velký pozor. Proslýchá se, že tam žije nevídané.</popis>
                                    <odmena>Pět zlatých</odmena>
                                </ukol>
                            </ukoly>
                        </interaktivni_postava>
                    </interaktivni_postavy>
                </frakce>
            </frakce_v_oblasti>
            <skupiny_nepratel>
                <skupina_nepratel n_nazev="Jezdci">
                    <vyskyt>východ</vyskyt>
                    <min_pocet_jedincu>5</min_pocet_jedincu>
                    <min_uroven_nepritele>13</min_uroven_nepritele>
                    <min_typ_odmeny>vzácná</min_typ_odmeny>
                </skupina_nepratel>
                <skupina_nepratel n_nazev="Lesní zvěř">
                    <vyskyt>celá oblast</vyskyt>
                    <min_pocet_jedincu>1</min_pocet_jedincu>
                    <min_uroven_nepritele>10</min_uroven_nepritele>
                    <min_typ_odmeny>střední</min_typ_odmeny>
                </skupina_nepratel>
                <skupina_nepratel n_nazev="Zbojníci">
                    <vyskyt>celá oblast</vyskyt>
                    <min_pocet_jedincu>2</min_pocet_jedincu>
                    <min_uroven_nepritele>10</min_uroven_nepritele>
                    <min_typ_odmeny>střední</min_typ_odmeny>
                </skupina_nepratel>
                <skupina_nepratel n_nazev="Zelení goblini">
                    <vyskyt>jih</vyskyt>
                    <min_pocet_jedincu>3</min_pocet_jedincu>
